MSVC needs boost namespace specified
error C2872: 'list': ambiguous symbol
'std::list': class has no constructors
'boost::python::ssize_t boost::python::len(const boost::python::api::object &)': cannot convert argument 1 from 'std::list' to 'const boost::python::api::object &'
binary '[': 'std::list' does not define this operator or a conversion to a type acceptable to the predefined operator
'arg': ambiguous symbol
'std::arg': no matching overloaded function found
'_Promote_to_float<_Ty>::type std::arg(_Ty)': could not deduce template argument for '<unnamed-symbol>'
'_Ty std::arg(const std::complex<_Other> &)': could not deduce template argument for 'const std::complex<_Other> &' from 'const char [5]'
'_Ty std::arg(const std::complex<_Other> &)': could not deduce template argument for 'const std::complex<_Other> &' from 'const char [10]'
'_Ty std::arg(const std::complex<_Other> &)': could not deduce template argument for 'const std::complex<_Other> &' from 'const char [6]'