GoboVisualiser : fix rebase
- it is necessary to add the non-anonymous namespace to avoid compiler error C2201: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2201?view=vs-2019
- static data in an anonymous namespace will get internal linkage, but LightFilterVisualiser comes from IECoreGLPreview which requires external linkage to access